/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkMergeAlertsIntoCaseRequest {
    #[serde(rename = "caseId")]
    pub case_id: String,
    #[serde(rename = "alertIds")]
    pub alert_ids: Vec<String>,
}

impl BulkMergeAlertsIntoCaseRequest {
    pub fn new(case_id: String, alert_ids: Vec<String>) -> BulkMergeAlertsIntoCaseRequest {
        BulkMergeAlertsIntoCaseRequest {
            case_id,
            alert_ids,
        }
    }
}

