/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CaseStatusValue {
    #[serde(rename = "New")]
    New,
    #[serde(rename = "InProgress")]
    InProgress,
    #[serde(rename = "Indeterminate")]
    Indeterminate,
    #[serde(rename = "FalsePositive")]
    FalsePositive,
    #[serde(rename = "TruePositive")]
    TruePositive,
    #[serde(rename = "Other")]
    Other,
    #[serde(rename = "Duplicated")]
    Duplicated,

}

impl std::fmt::Display for CaseStatusValue {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::New => write!(f, "New"),
            Self::InProgress => write!(f, "InProgress"),
            Self::Indeterminate => write!(f, "Indeterminate"),
            Self::FalsePositive => write!(f, "FalsePositive"),
            Self::TruePositive => write!(f, "TruePositive"),
            Self::Other => write!(f, "Other"),
            Self::Duplicated => write!(f, "Duplicated"),
        }
    }
}

impl Default for CaseStatusValue {
    fn default() -> CaseStatusValue {
        Self::New
    }
}

