/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindEntitiesByQueryRequest {
    InputQuery(Box<models::InputQuery>),
    /// An empty JSON array. Used for fetching all entities of a given type (e.g., all cases, all alerts) when no specific query operations are provided.
    Array(Vec<serde_json::Value>),
}

impl Default for FindEntitiesByQueryRequest {
    fn default() -> Self {
        Self::InputQuery(Default::default())
    }
}

