/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FindEntitiesByQuery200Response {
    Array(Vec<serde_json::Value>),
    Integer(i32),
    Object(serde_json::Value),
}

impl Default for FindEntitiesByQuery200Response {
    fn default() -> Self {
        Self::Array(Default::default())
    }
}

