/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImpactStatusValue {
    #[serde(rename = "NotApplicable")]
    NotApplicable,
    #[serde(rename = "WithImpact")]
    WithImpact,
    #[serde(rename = "NoImpact")]
    NoImpact,

}

impl std::fmt::Display for ImpactStatusValue {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NotApplicable => write!(f, "NotApplicable"),
            Self::WithImpact => write!(f, "WithImpact"),
            Self::NoImpact => write!(f, "NoImpact"),
        }
    }
}

impl Default for ImpactStatusValue {
    fn default() -> ImpactStatusValue {
        Self::NotApplicable
    }
}

