/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputQuery {
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Vec<models::QueryOperation>>,
    #[serde(rename = "excludeFields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exclude_fields: Option<Option<Vec<String>>>,
}

impl InputQuery {
    pub fn new() -> InputQuery {
        InputQuery {
            query: None,
            exclude_fields: None,
        }
    }
}

