/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputAnalyzerJob {
    #[serde(rename = "analyzerId")]
    pub analyzer_id: String,
    #[serde(rename = "cortexId")]
    pub cortex_id: String,
    #[serde(rename = "artifactId")]
    pub artifact_id: String,
    #[serde(rename = "parameters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl InputAnalyzerJob {
    pub fn new(analyzer_id: String, cortex_id: String, artifact_id: String) -> InputAnalyzerJob {
        InputAnalyzerJob {
            analyzer_id,
            cortex_id,
            artifact_id,
            parameters: None,
        }
    }
}

