/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputResponderAction {
    #[serde(rename = "objectId")]
    pub object_id: String,
    #[serde(rename = "objectType")]
    pub object_type: String,
    #[serde(rename = "responderId")]
    pub responder_id: String,
    #[serde(rename = "parameters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "tlp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tlp: Option<Option<i32>>,
}

impl InputResponderAction {
    pub fn new(object_id: String, object_type: String, responder_id: String) -> InputResponderAction {
        InputResponderAction {
            object_id,
            object_type,
            responder_id,
            parameters: None,
            tlp: None,
        }
    }
}

