/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputUpdateTaskLog {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "includeInTimeline", skip_serializing_if = "Option::is_none")]
    pub include_in_timeline: Option<bool>,
}

impl InputUpdateTaskLog {
    pub fn new() -> InputUpdateTaskLog {
        InputUpdateTaskLog {
            message: None,
            include_in_timeline: None,
        }
    }
}

