/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputBulkOrganisationLink {
    #[serde(rename = "toOrganisation")]
    pub to_organisation: String,
    #[serde(rename = "linkType")]
    pub link_type: String,
    #[serde(rename = "otherLinkType")]
    pub other_link_type: String,
}

impl InputBulkOrganisationLink {
    pub fn new(to_organisation: String, link_type: String, other_link_type: String) -> InputBulkOrganisationLink {
        InputBulkOrganisationLink {
            to_organisation,
            link_type,
            other_link_type,
        }
    }
}

