/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputOrganisationLink {
    #[serde(rename = "linkType", skip_serializing_if = "Option::is_none")]
    pub link_type: Option<String>,
    #[serde(rename = "otherLinkType", skip_serializing_if = "Option::is_none")]
    pub other_link_type: Option<String>,
}

impl InputOrganisationLink {
    pub fn new() -> InputOrganisationLink {
        InputOrganisationLink {
            link_type: None,
            other_link_type: None,
        }
    }
}

