/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputProcedure {
    /// Epoch milliseconds
    #[serde(rename = "occurDate")]
    pub occur_date: i64,
    /// MITRE ATT&CK pattern ID (e.g., T1566)
    #[serde(rename = "patternId")]
    pub pattern_id: String,
    #[serde(rename = "tactic", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tactic: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl InputProcedure {
    pub fn new(occur_date: i64, pattern_id: String) -> InputProcedure {
        InputProcedure {
            occur_date,
            pattern_id,
            tactic: None,
            description: None,
        }
    }
}

