/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputUpdateProcedure {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "occurDate", skip_serializing_if = "Option::is_none")]
    pub occur_date: Option<i64>,
}

impl InputUpdateProcedure {
    pub fn new() -> InputUpdateProcedure {
        InputUpdateProcedure {
            description: None,
            occur_date: None,
        }
    }
}

