/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputUpdateObservable {
    #[serde(rename = "dataType", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "tlp", skip_serializing_if = "Option::is_none")]
    pub tlp: Option<i32>,
    #[serde(rename = "pap", skip_serializing_if = "Option::is_none")]
    pub pap: Option<i32>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "ioc", skip_serializing_if = "Option::is_none")]
    pub ioc: Option<bool>,
    #[serde(rename = "sighted", skip_serializing_if = "Option::is_none")]
    pub sighted: Option<bool>,
    #[serde(rename = "sightedAt", skip_serializing_if = "Option::is_none")]
    pub sighted_at: Option<i64>,
    #[serde(rename = "ignoreSimilarity", skip_serializing_if = "Option::is_none")]
    pub ignore_similarity: Option<bool>,
}

impl InputUpdateObservable {
    pub fn new() -> InputUpdateObservable {
        InputUpdateObservable {
            data_type: None,
            message: None,
            tlp: None,
            pap: None,
            tags: None,
            ioc: None,
            sighted: None,
            sighted_at: None,
            ignore_similarity: None,
        }
    }
}

