/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MergeAlertIntoCaseCaseIdParameter {
    String(String),
    Integer(i32),
}

impl Default for MergeAlertIntoCaseCaseIdParameter {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

