/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputAttachment {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "_type")]
    pub _type: String,
    #[serde(rename = "_createdBy")]
    pub _created_by: String,
    #[serde(rename = "_createdAt")]
    pub _created_at: i64,
    #[serde(rename = "_updatedBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _updated_by: Option<Option<String>>,
    #[serde(rename = "_updatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _updated_at: Option<Option<i64>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "contentType")]
    pub content_type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "hashes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hashes: Option<Option<Vec<String>>>,
}

impl OutputAttachment {
    pub fn new(_id: String, _type: String, _created_by: String, _created_at: i64, name: String, size: i32, content_type: String, id: String) -> OutputAttachment {
        OutputAttachment {
            _id,
            _type,
            _created_by,
            _created_at,
            _updated_by: None,
            _updated_at: None,
            name,
            size,
            content_type,
            id,
            hashes: None,
        }
    }
}

