/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputUserOrganisation {
    #[serde(rename = "organisation")]
    pub organisation: String,
    #[serde(rename = "profile")]
    pub profile: String,
    #[serde(rename = "default")]
    pub default: bool,
}

impl OutputUserOrganisation {
    pub fn new(organisation: String, profile: String, default: bool) -> OutputUserOrganisation {
        OutputUserOrganisation {
            organisation,
            profile,
            default,
        }
    }
}

