/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputCase {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "_type")]
    pub _type: String,
    #[serde(rename = "_createdBy")]
    pub _created_by: String,
    #[serde(rename = "_createdAt")]
    pub _created_at: i64,
    #[serde(rename = "_updatedBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _updated_by: Option<Option<String>>,
    #[serde(rename = "_updatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _updated_at: Option<Option<i64>>,
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "severity")]
    pub severity: i32,
    #[serde(rename = "severityLabel")]
    pub severity_label: String,
    #[serde(rename = "startDate")]
    pub start_date: i64,
    #[serde(rename = "endDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<Option<i64>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
    #[serde(rename = "flag")]
    pub flag: bool,
    #[serde(rename = "tlp")]
    pub tlp: i32,
    #[serde(rename = "tlpLabel")]
    pub tlp_label: String,
    #[serde(rename = "pap")]
    pub pap: i32,
    #[serde(rename = "papLabel")]
    pub pap_label: String,
    #[serde(rename = "status")]
    pub status: models::CaseStatusValue,
    #[serde(rename = "stage")]
    pub stage: String,
    #[serde(rename = "summary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Option<String>>,
    #[serde(rename = "impactStatus", skip_serializing_if = "Option::is_none")]
    pub impact_status: Option<models::ImpactStatusValue>,
    #[serde(rename = "assignee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<Option<String>>,
    #[serde(rename = "customFields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Option<Vec<models::OutputCustomFieldValue>>>,
    #[serde(rename = "userPermissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_permissions: Option<Option<Vec<String>>>,
    #[serde(rename = "extraData")]
    pub extra_data: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "newDate")]
    pub new_date: i64,
    #[serde(rename = "inProgressDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_progress_date: Option<Option<i64>>,
    #[serde(rename = "closedDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub closed_date: Option<Option<i64>>,
    #[serde(rename = "alertDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alert_date: Option<Option<i64>>,
    #[serde(rename = "alertNewDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alert_new_date: Option<Option<i64>>,
    #[serde(rename = "alertInProgressDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alert_in_progress_date: Option<Option<i64>>,
    #[serde(rename = "alertImportedDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alert_imported_date: Option<Option<i64>>,
    #[serde(rename = "timeToDetect")]
    pub time_to_detect: i64,
    #[serde(rename = "timeToTriage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_to_triage: Option<Option<i64>>,
    #[serde(rename = "timeToQualify", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_to_qualify: Option<Option<i64>>,
    #[serde(rename = "timeToAcknowledge", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_to_acknowledge: Option<Option<i64>>,
    #[serde(rename = "timeToResolve", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_to_resolve: Option<Option<i64>>,
    #[serde(rename = "handlingDuration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub handling_duration: Option<Option<i64>>,
}

impl OutputCase {
    pub fn new(_id: String, _type: String, _created_by: String, _created_at: i64, number: i32, title: String, description: String, severity: i32, severity_label: String, start_date: i64, flag: bool, tlp: i32, tlp_label: String, pap: i32, pap_label: String, status: models::CaseStatusValue, stage: String, extra_data: std::collections::HashMap<String, serde_json::Value>, new_date: i64, time_to_detect: i64) -> OutputCase {
        OutputCase {
            _id,
            _type,
            _created_by,
            _created_at,
            _updated_by: None,
            _updated_at: None,
            number,
            title,
            description,
            severity,
            severity_label,
            start_date,
            end_date: None,
            tags: None,
            flag,
            tlp,
            tlp_label,
            pap,
            pap_label,
            status,
            stage,
            summary: None,
            impact_status: None,
            assignee: None,
            custom_fields: None,
            user_permissions: None,
            extra_data,
            new_date,
            in_progress_date: None,
            closed_date: None,
            alert_date: None,
            alert_new_date: None,
            alert_in_progress_date: None,
            alert_imported_date: None,
            time_to_detect,
            time_to_triage: None,
            time_to_qualify: None,
            time_to_acknowledge: None,
            time_to_resolve: None,
            handling_duration: None,
        }
    }
}

