/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputTaskLog {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "_type")]
    pub _type: String,
    #[serde(rename = "_createdBy")]
    pub _created_by: String,
    #[serde(rename = "_createdAt")]
    pub _created_at: i64,
    #[serde(rename = "_updatedBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _updated_by: Option<Option<String>>,
    #[serde(rename = "_updatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _updated_at: Option<Option<i64>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "date")]
    pub date: i64,
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<models::OutputAttachment>>>,
    #[serde(rename = "includeInTimeline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub include_in_timeline: Option<Option<bool>>,
    #[serde(rename = "extraData")]
    pub extra_data: std::collections::HashMap<String, serde_json::Value>,
}

impl OutputTaskLog {
    pub fn new(_id: String, _type: String, _created_by: String, _created_at: i64, message: String, date: i64, owner: String, extra_data: std::collections::HashMap<String, serde_json::Value>) -> OutputTaskLog {
        OutputTaskLog {
            _id,
            _type,
            _created_by,
            _created_at,
            _updated_by: None,
            _updated_at: None,
            message,
            date,
            owner,
            attachments: None,
            include_in_timeline: None,
            extra_data,
        }
    }
}

