/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputOrganisationProfile {
    #[serde(rename = "organisationId")]
    pub organisation_id: String,
    #[serde(rename = "organisation")]
    pub organisation: String,
    #[serde(rename = "profile")]
    pub profile: String,
}

impl OutputOrganisationProfile {
    pub fn new(organisation_id: String, organisation: String, profile: String) -> OutputOrganisationProfile {
        OutputOrganisationProfile {
            organisation_id,
            organisation,
            profile,
        }
    }
}

