/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFilterLtAllOfLt {
    #[serde(rename = "_field", skip_serializing_if = "Option::is_none")]
    pub _field: Option<String>,
    #[serde(rename = "_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _value: Option<Option<serde_json::Value>>,
}

impl QueryFilterLtAllOfLt {
    pub fn new() -> QueryFilterLtAllOfLt {
        QueryFilterLtAllOfLt {
            _field: None,
            _value: None,
        }
    }
}

