/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryFilterLt {
    #[serde(rename = "_lt", skip_serializing_if = "Option::is_none")]
    pub _lt: Option<Box<models::QueryFilterLtAllOfLt>>,
}

impl QueryFilterLt {
    pub fn new() -> QueryFilterLt {
        QueryFilterLt {
            _lt: None,
        }
    }
}

