/*
 * TheHive API
 *
 * Comprehensive OpenAPI specification inferred from the TheHive4py client library. This API allows interaction with TheHive platform for managing alerts, cases, observables, tasks, users, and other entities. 
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryPaginate {
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<i32>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<i32>,
    #[serde(rename = "extraData", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<Option<Vec<serde_json::Value>>>,
}

impl QueryPaginate {
    pub fn new() -> QueryPaginate {
        QueryPaginate {
            from: None,
            to: None,
            extra_data: None,
        }
    }
}

